//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo.AUDITORIA
{
    using System;
    using System.Collections.Generic;
    
    public partial class AudGasto
    {
        public int Id { get; set; }
        public int IdGasto { get; set; }
        public string Descripcion { get; set; }
        public decimal Monto { get; set; }
        public string Estado { get; set; }
        public System.DateTime FechaVencimiento { get; set; }
        public Nullable<System.DateTime> HoraEmision { get; set; }
        public Nullable<System.DateTime> FechaEmision { get; set; }
        public int TipoGasto { get; set; }
        public string Vehiculo { get; set; }
        public string Usuario { get; set; }
        public System.DateTime FechayHora { get; set; }
        public string Operacion { get; set; }
    }
}
