//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo.AUDITORIA
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginLogout
    {
        public int Id { get; set; }
        public string Usuario { get; set; }
        public System.DateTime FechayHora { get; set; }
        public string Operacion { get; set; }
    }
}
