//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo.AUDITORIA
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Sist_Flota_ModeloAuditoriaContainer : DbContext
    {
        public Sist_Flota_ModeloAuditoriaContainer()
            : base("name=Sist_Flota_ModeloAuditoriaContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AudGasto> AudGastos { get; set; }
        public virtual DbSet<LoginLogout> LogInsOuts { get; set; }
    }
}
