//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo.AUDITORIA
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Sist_Flota_ModeloAuditoriaContainer : DbContext
    {
        public Sist_Flota_ModeloAuditoriaContainer()
            : base("name=Sist_Flota_ModeloAuditoriaContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AudGasto> AudGastos { get; set; }
        public virtual DbSet<LoginLogout> LogInsOuts { get; set; }
    }
}
