//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo.SEGURIDAD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Perfil
    {
        public int IDPerfil { get; set; }
    
        public virtual Grupo Grupo { get; set; }
        public virtual Permiso Permiso { get; set; }
        public virtual Formulario Formulario { get; set; }
    }
}
