//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo.SEGURIDAD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.Habilitado = true;
            this.Online = false;
            this.PrimeraVez = true;
            this.Activo = 1;
            this.Grupo = new HashSet<Grupo>();
        }
    
        public string IDUsuario { get; set; }
        public string NombreApellido { get; set; }
        public string Contraseña { get; set; }
        public string Email { get; set; }
        public bool Habilitado { get; set; }
        public bool Online { get; set; }
        public bool PrimeraVez { get; set; }
        public short Activo { get; set; }
    
        public virtual ICollection<Grupo> Grupo { get; set; }
        public virtual Flota Flota { get; set; }
    }
}
