//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuentaCorriente
    {
        public CuentaCorriente()
        {
            this.Activo = 1;
        }
    
        public int Id { get; set; }
        public System.DateTime Fecha { get; set; }
        public decimal Monto { get; set; }
        public string Estado { get; set; }
        public int fIDFlota { get; set; }
        public short Activo { get; set; }
    
        public virtual Turno Turno { get; set; }
        public virtual Empresa Empresa { get; set; }
    }
}
