//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empresa
    {
        public Empresa()
        {
            this.CuentaCorriente = new HashSet<CuentaCorriente>();
        }
    
        public int Cuit { get; set; }
        public string RazonSocial { get; set; }
        public string Domicilio { get; set; }
        public string Telefono { get; set; }
        public string Localidad { get; set; }
        public string Correo { get; set; }
    
        public virtual ICollection<CuentaCorriente> CuentaCorriente { get; set; }
    }
}
