//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gasto
    {
        public int Id { get; set; }
        public string Descripcion { get; set; }
        public decimal Monto { get; set; }
        public string Estado { get; set; }
        public System.DateTime FechaVencimiento { get; set; }
        public Nullable<System.DateTime> HoraEmision { get; set; }
        public Nullable<System.DateTime> FechaEmision { get; set; }
        public string Usuario { get; set; }
        public Nullable<System.DateTime> FechayHora { get; set; }
        public string Operacion { get; set; }
        public string fIDFlota { get; set; }
        public string Activo { get; set; }
    
        public virtual TipodeGasto TipodeGasto { get; set; }
        public virtual Vehiculo Vehiculo { get; set; }
        public virtual Turno Turno { get; set; }
    }
}
