//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SistFlota_ModeloDatosContainer : DbContext
    {
        public SistFlota_ModeloDatosContainer()
            : base("name=SistFlota_ModeloDatosContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TipodeGasto> TiposdeGasto { get; set; }
        public virtual DbSet<Gasto> Gastos { get; set; }
        public virtual DbSet<Vehiculo> Vehiculos { get; set; }
    }
}
