//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Turno
    {
        public Turno()
        {
            this.Gasto = new HashSet<Gasto>();
        }
    
        public int Id { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public System.DateTime HoraInicio { get; set; }
        public System.DateTime FechaFin { get; set; }
        public System.DateTime HoraFin { get; set; }
        public decimal KmRecorridos { get; set; }
        public decimal KmOcupados { get; set; }
        public int CantidadViajes { get; set; }
        public decimal RecaudacionEfectivo { get; set; }
        public string Comentarios { get; set; }
        public Nullable<int> GastoId { get; set; }
    
        public virtual Vehiculo Vehiculo { get; set; }
        public virtual Chofer Chofer { get; set; }
        public virtual ICollection<Gasto> Gasto { get; set; }
    }
}
